services:
  db:
    image: mysql:8.0 
    container_name: book-manager
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: book_manager 
      MYSQL_USER: huuloc2026 
      MYSQL_PASSWORD: 123456 
    ports:
      - "3306:3306" 
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
